name: Despliegue en Azure

on:
  push:
    branches:
      - develop # Cambia esto al nombre de tu rama principal

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código fuente
        uses: actions/checkout@v2

      - name: Login en Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Construir la imagen Docker
        run: docker build -t fedeveron2/factory:latest -f .Dockerfile .

      - name: Push de la imagen a Docker Hub
        run: docker push fedeveron2/factory:latest

      - name: SSH a tu VPS en Azure
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: 22
          script: |
            # Detener y eliminar el contenedor existente
            docker stop factory || true
            docker rm factory || true

            # Descargar la nueva versión de la imagen
            docker pull fedeveron2/factory:latest

            # Crear y ejecutar el contenedor en el puerto 8080
            docker run -d -p 8080:8080 --name factory fedeveron2/factory:latest
